### ISSUE TITLE
version without ligatures?

### ISSUE THREAD

**Issue by codic12** [belluzj/fantasque-sans#136] opened 2020-07-19 00:22 UTC
if this exists, i can't find it. how can i compile from source without ligatures? 

cc: @belluzj

**Comment by kbauer** [comment] 2020-10-21 13:44
Duplicate of https://github.com/belluzj/fantasque-sans/issues/122?

**Closed** 2020-10-21 16:36 UTC

**Comment by spinda** [comment] 2021-12-30 20:24
I've put up a fork at https://github.com/spinda/fantasque-sans-ligatures that strips out everything from v1.8.0 relating to the new coding ligatures.
