### ISSUE TITLE
Ligatures please

### ISSUE THREAD

**Issue by tadvi** [belluzj/fantasque-sans#80] opened 2017-06-19 11:32 UTC
Awesome font but no ligatures. Would be nice to have ligatures for "!=" and "<-" .

**Comment by dayfuaim** [comment] 2017-07-13 08:37
Yes, I confirm this.
Also "->", "=>", "..".

Please. :)

**Comment by Demonstrandum** [comment] 2017-08-24 16:56
Perhaps as many as [/tonsky/FiraCode](https://github.com/tonsky/FiraCode) has? One of the things I wish Fantasque had.

**Comment by soviet-man** [comment] 2017-11-22 11:17
Please do not implement ligatures. Ligatures looks nice BUT they may confuse. For example, minus + more = right arrow. But there is already unicode symbol like arrow.

**Comment by Demonstrandum** [comment] 2017-11-22 14:39
@soviet-man
No, just an __option__ for ligatures.
I don't see how it's confusing, those are the symbols they're ment to represent.

Also, unicode symbols aren't always understood by the compiler/interpreter, and thus would require a preprocessor, which just adds extra hassle. 

Fira Code manages to pull it off perfectly well.

**Comment by belluzj** [comment] 2017-11-22 14:45
Yes of course, when I take the time to do that, I will provide it as an option. And anyway, the font is open-source, it should be easy to build a version without the ligature code. Apart from that, I'm sorry but I have no ETA for this feature but I definitely will work on it at some point!

**Comment by belluzj** [comment] 2018-01-07 00:12
Closed because it's a duplicate of #64

**Closed by belluzj** 2018-01-07 00:12 UTC
